// Code generated by protoc-gen-go.
// source: swedish.proto
// DO NOT EDIT!

/*
Package swedish is a generated protocol buffer package.

Expose an api to translate english to swedish

It is generated from these files:
	swedish.proto

It has these top-level messages:
	TranslateRequest
	TranslateResponse
*/
package swedish

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/serviceconfig"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TranslateRequest struct {
	Phrase string `protobuf:"bytes,1,opt,name=Phrase" json:"Phrase,omitempty"`
}

func (m *TranslateRequest) Reset()                    { *m = TranslateRequest{} }
func (m *TranslateRequest) String() string            { return proto.CompactTextString(m) }
func (*TranslateRequest) ProtoMessage()               {}
func (*TranslateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TranslateRequest) GetPhrase() string {
	if m != nil {
		return m.Phrase
	}
	return ""
}

type TranslateResponse struct {
	Value string `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
}

func (m *TranslateResponse) Reset()                    { *m = TranslateResponse{} }
func (m *TranslateResponse) String() string            { return proto.CompactTextString(m) }
func (*TranslateResponse) ProtoMessage()               {}
func (*TranslateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TranslateResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TranslateRequest)(nil), "swedish.TranslateRequest")
	proto.RegisterType((*TranslateResponse)(nil), "swedish.TranslateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Swedish service

type SwedishClient interface {
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error)
}

type swedishClient struct {
	cc *grpc.ClientConn
}

func NewSwedishClient(cc *grpc.ClientConn) SwedishClient {
	return &swedishClient{cc}
}

func (c *swedishClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error) {
	out := new(TranslateResponse)
	err := grpc.Invoke(ctx, "/swedish.Swedish/Translate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Swedish service

type SwedishServer interface {
	Translate(context.Context, *TranslateRequest) (*TranslateResponse, error)
}

func RegisterSwedishServer(s *grpc.Server, srv SwedishServer) {
	s.RegisterService(&_Swedish_serviceDesc, srv)
}

func _Swedish_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwedishServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swedish.Swedish/Translate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwedishServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Swedish_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swedish.Swedish",
	HandlerType: (*SwedishServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Translate",
			Handler:    _Swedish_Translate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swedish.proto",
}

func init() { proto.RegisterFile("swedish.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0xe0, 0xae, 0x1b, 0x58, 0xd0, 0x28, 0xa2, 0x3d, 0x49, 0x4f, 0xba, 0x87, 0x04,
	0xf4, 0xe6, 0x1b, 0x78, 0x93, 0x55, 0xf4, 0x3c, 0xad, 0x63, 0x1a, 0x08, 0x33, 0x31, 0x93, 0xea,
	0xdd, 0x57, 0xf0, 0xd1, 0x7c, 0x05, 0x1f, 0x44, 0x68, 0x5a, 0x11, 0xf1, 0xf8, 0xf1, 0x7f, 0xc9,
	0x3f, 0xbf, 0x5a, 0xcb, 0x1b, 0x3e, 0x79, 0xe9, 0x4d, 0x4c, 0x9c, 0x59, 0x2f, 0x27, 0xac, 0x6f,
	0x1c, 0xb3, 0x0b, 0x68, 0x1c, 0x07, 0x20, 0x67, 0x38, 0x39, 0xeb, 0x90, 0x46, 0xc9, 0x96, 0x08,
	0xa2, 0x17, 0x0b, 0xd1, 0x5b, 0xc1, 0xf4, 0xea, 0x3b, 0xec, 0x98, 0x9e, 0xbd, 0xb3, 0x40, 0xc4,
	0x19, 0xb2, 0x67, 0x92, 0xf2, 0x67, 0xb3, 0x51, 0xfb, 0xf7, 0x09, 0x48, 0x02, 0x64, 0xdc, 0xe2,
	0xcb, 0x80, 0x92, 0xf5, 0xb1, 0x5a, 0xdc, 0xf6, 0x09, 0x04, 0x4f, 0xaa, 0xb3, 0xea, 0x7c, 0xb5,
	0x9d, 0xa8, 0xb9, 0x50, 0x07, 0xbf, 0x5c, 0x89, 0x4c, 0x82, 0xfa, 0x48, 0xed, 0x3e, 0x40, 0x18,
	0x66, 0xb7, 0xc0, 0x65, 0xab, 0x96, 0x77, 0xe5, 0x58, 0xfd, 0xa8, 0x56, 0x3f, 0xaf, 0xf4, 0xa9,
	0x99, 0x27, 0xfd, 0x6d, 0xad, 0xeb, 0xff, 0xa2, 0x52, 0xd2, 0x1c, 0xbe, 0x7f, 0x7e, 0x7d, 0xec,
	0xac, 0xf5, 0x9e, 0x9d, 0x9c, 0xeb, 0x6a, 0xd3, 0x2e, 0xc6, 0x05, 0x57, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x19, 0xba, 0xfe, 0xdb, 0x26, 0x01, 0x00, 0x00,
}
