// Code generated by protoc-gen-go.
// source: gateway.proto
// DO NOT EDIT!

/*
Package gateway is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	TranslateRequest
	TranslateResponse
*/
package gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/serviceconfig"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TranslateRequest struct {
	Phrase    string   `protobuf:"bytes,1,opt,name=Phrase" json:"Phrase,omitempty"`
	Languages []string `protobuf:"bytes,2,rep,name=Languages" json:"Languages,omitempty"`
}

func (m *TranslateRequest) Reset()                    { *m = TranslateRequest{} }
func (m *TranslateRequest) String() string            { return proto.CompactTextString(m) }
func (*TranslateRequest) ProtoMessage()               {}
func (*TranslateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TranslateRequest) GetPhrase() string {
	if m != nil {
		return m.Phrase
	}
	return ""
}

func (m *TranslateRequest) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

type TranslateResponse struct {
	Value string `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
}

func (m *TranslateResponse) Reset()                    { *m = TranslateResponse{} }
func (m *TranslateResponse) String() string            { return proto.CompactTextString(m) }
func (*TranslateResponse) ProtoMessage()               {}
func (*TranslateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TranslateResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TranslateRequest)(nil), "gateway.TranslateRequest")
	proto.RegisterType((*TranslateResponse)(nil), "gateway.TranslateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gateway service

type GatewayClient interface {
	// Echo "echos" the incoming string
	Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Translate(ctx context.Context, in *TranslateRequest, opts ...grpc.CallOption) (*TranslateResponse, error) {
	out := new(TranslateResponse)
	err := grpc.Invoke(ctx, "/gateway.Gateway/Translate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gateway service

type GatewayServer interface {
	// Echo "echos" the incoming string
	Translate(context.Context, *TranslateRequest) (*TranslateResponse, error)
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Translate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Translate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.Gateway/Translate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Translate(ctx, req.(*TranslateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Translate",
			Handler:    _Gateway_Translate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xa5, 0x2d, 0x59, 0x10, 0xea, 0x22, 0x52, 0x83, 0x87, 0x92, 0x53, 0xf5, 0x90,
	0x05, 0xbd, 0xf9, 0x02, 0x2a, 0x78, 0x90, 0x50, 0xbc, 0xca, 0x18, 0xc6, 0xe9, 0x42, 0x98, 0x89,
	0x3b, 0x1b, 0xc5, 0xab, 0xaf, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0xd0, 0x6d, 0x54, 0xa4, 0xc7,
	0x7f, 0xff, 0x9d, 0x6f, 0xe6, 0x33, 0xfb, 0x04, 0x11, 0x5f, 0xe1, 0xad, 0xea, 0x82, 0x44, 0xb1,
	0xd3, 0x6d, 0x2c, 0x6e, 0x48, 0x84, 0x5a, 0xac, 0x48, 0x5a, 0x60, 0xaa, 0x24, 0x90, 0x23, 0xe4,
	0xcd, 0x27, 0x97, 0x2a, 0xe8, 0xbc, 0x3a, 0xe8, 0xbc, 0x53, 0x0c, 0x2f, 0xbe, 0xc1, 0x46, 0xf8,
	0xc9, 0x93, 0x03, 0x66, 0x89, 0x10, 0xbd, 0xb0, 0x26, 0x66, 0x79, 0x6d, 0x66, 0xab, 0x00, 0xac,
	0x2d, 0x44, 0xac, 0xf1, 0xb9, 0x47, 0x8d, 0xf6, 0xc8, 0x4c, 0xee, 0xd6, 0x01, 0x14, 0xe7, 0xd9,
	0x22, 0x5b, 0xe6, 0xf5, 0x36, 0xd9, 0x13, 0x93, 0xdf, 0x02, 0x53, 0x0f, 0x84, 0x3a, 0x1f, 0x2d,
	0xf6, 0x96, 0x79, 0xfd, 0xfb, 0x50, 0x9e, 0x9a, 0x83, 0x3f, 0x24, 0xed, 0x84, 0x15, 0xed, 0xa1,
	0x19, 0xdf, 0x43, 0xdb, 0x0f, 0xa4, 0x14, 0xce, 0x1f, 0xcc, 0xf4, 0x2a, 0xa9, 0xd8, 0x95, 0xc9,
	0x7f, 0xa6, 0xec, 0x71, 0x35, 0x08, 0xff, 0xbf, 0xa9, 0x28, 0x76, 0x55, 0x69, 0x49, 0x39, 0x7b,
	0xff, 0xfc, 0xfa, 0x18, 0x19, 0x3b, 0x76, 0xd8, 0xac, 0xe5, 0x32, 0x3b, 0x7b, 0x9c, 0x6c, 0xe4,
	0x2e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x63, 0x5a, 0xe5, 0xc8, 0x41, 0x01, 0x00, 0x00,
}
